apiVersion: v1
kind: Service
metadata:
  name: {{ include "messageflowapp.fullname" . }}
  labels:
    {{- include "messageflowapp.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
   - port: 8080
     nodePort: 30081
  selector:
    {{- include "messageflowapp.selectorLabels" . | nindent 4 }}
