apiVersion: v1
kind: ConfigMap
metadata:
  name: messageflowapp-config
  labels:
    app: messageflowapp
data:
  application.properties: |-
    spring.datasource.url=jdbc:postgresql://kubernetes.docker.internal:30080/postgres
    spring.datasource.username=postgresadmin
    spring.datasource.password=root 

